### ISSUE TITLE
Hidden channels are not hidden on Push 2

### ISSUE THREAD

**Issue by giacecco** [git-moss/DrivenByMoss-Documentation#19]
Hi Moss, All,
I don't know if this is a bug or a limitation of the information Bitwig offers scripts. I've searched past issues and could not find a reference to this. I'm running the latest DrivenByMoss at the moment of writing, 10.6.4.

When one hides a deactivated channel in Bitwig Studio 3.2.7, the channel still shows in Push 2. 

To reproduce:
- in mix mode, deactivate any track
- right-click on the Bitwig window background and toggle "Show deactivated channels" off

... and the channel will be hidden in Bitwig but still visible on Push 2.

This is inconvenient, because - unless one puts all deactivated channels to the extreme right - it creates a visual difference in how the channels are shown on Push and how they are shown on screen. Thanks!

**Comment by git-moss** [comment]
That is a limitation of the API. You can work around it a bit if you active to hide deactivated tracks in the Push 2 settings.
