### ISSUE TITLE
Extensions Directory

### ISSUE THREAD

**Issue by dherndon** [git-moss/DrivenByMoss-Documentation#2]
I had to copy your extension for SL MK III into the c:\program files\Bitwig Studio\Resources\BitWig Extensions folder before my installlation would see it.

You had indicated it should be under:

Copy that file in the following location depending on your OS:
Windows: %USERPROFILE%\Documents\Bitwig Studio\Extensions\

**Comment by git-moss** [comment]
That is the correct folder. Can you post the full path wher you put it? Do you mabe have multiple users on your system?

**Comment by dherndon** [comment]
I have a demo version, maybe that matters.    I also went through a process since installation, of removing OneDrive which had mapped my documents.     

But it absolutely would not pick up the extension until I put it under \Program Files.,....

Thank for the work on this.....made me think i might use Bitwig instead of Abelton.   

![moss](https://user-images.githubusercontent.com/16982545/78667596-41617900-78a7-11ea-94ab-885f8ced880b.JPG)
