### ISSUE TITLE
Launchpad Pro MK3 Note/Chord/Sequencer not working

### ISSUE THREAD

**Issue by MeditoDiTerra** [git-moss/DrivenByMoss-Documentation#20]
I have the latest Bitwig 3.2.8 and the latest Pro MK3 firmware 1.2, running on Win 10 Pro.

The issue is that it's not possible to freely switch between Note/Drum Sequencer[Chord]/Note Sequencer modes. It only works once, and than it gets stuck on the selected mode, no matter which. The only way to change modes again is to turn off and on the controller in the Bitwig settings, than it allows to switch to a different mode, but only once again.

The way the Pro MK3 is implemented in Bitwig is amazing and could easily surpass the native Ableton Live implementation, if these modes worked, but having to go to the settings every time I need to switch to a different mode renders the script pretty much useless.

Anyone else having these issues?

**Comment by brunobeltran** [comment]
Came here to report a very similar issue.

I find that if I switch between different tracks, it allows you to switch modes once more, but then never again, almost like it's actually only one mode allowed per track...

Only being able to switch modes once per track would not be the worst bug ever, as it would be easy to work around. But I also find that actually the sequencer modes don't "work" at all, even if I manage to make them appear. 

@MDTxxx, are the sequencer modes (the ones you get by hitting "Chord", according to the [YouTube demo](https://www.youtube.com/watch?v=mkpu-Na5rVM)) working for you? For me, the drum pad or whatever will appear, but the actual sequencer tracks (the top half of the pads) stay unlit and do not appear to work.

**Comment by git-moss** [comment]
Yes, got this report already on KVR. Will be fixed in the next update.

**Comment by MeditoDiTerra** [comment]
Cool, is there a previous version I could roll back to in the meantime? I know it had some issues with restoring, but that is a minor inconvenience compared to not being able to switch modes altogether.

Also, I can see you put immense amount of work into this project, yet it's available for free and there's no even donation option. What keeps you so motivated to constantly update it and respond to all our requests?

**Comment by git-moss** [comment]
The update will be available later today.

I must be insane :-)

**Comment by MeditoDiTerra** [comment]
Unbelievable!
I sure hope Bitwig treats you to it somehow, cause you're doing them an enormous favor!

**Comment by renderful** [comment]
I'm still having this issue on the newest release of DrivenByMoss on Bitwig 3.2.8 on Launchpad Pro mk3 with newest firmware. Thanks! Love the software.
