### ISSUE TITLE
Launchpad pro mk3 documentation?

### ISSUE THREAD

**Issue by nnbveh** [git-moss/DrivenByMoss-Documentation#22]
Hi, i'm trying to follow the documentation for launchpads but it's confusing from the start...

"Click - Toggle the metronome...Shift+Click - Tap Tempo" - Shift+click is toggle the metronome on mk3, where is tap tempo then?
"Delete - Hold the button for additional functionality in combination with other buttons knobs, see the view explanations below." There's NO delete button on mk3, which one we use instead...

Also all the illustrations are for launchpad x only, would be nice to see mk3 as well, much easier to visualize and remember all the controls...

Thanks for great job done anyways!!

**Comment by git-moss** [comment]
Section 20.2 explains the differences of Launchpad nideks. Especially for the Pro Mk3 see section 20.2.1.
There is also an introduction video on my Youtube channel: https://www.youtube.com/watch?v=mkpu-Na5rVM
Hope that helps.
