### ISSUE TITLE
Navigating tracks in Bitwig with Push when using Groups

### ISSUE THREAD

**Issue by junglegobs** [git-moss/DrivenByMoss-Documentation#27]
I use groups quite a lot, e.g. for putting all my drum tracks into the same group. As far as I can tell, there's no way of going "up" a group level - the only way is to press "Track", which will take me to the effect tracks, then press it again at which point I'm at the top layer of the groups again. This is a bit annoying, and it seems to me that this could be achieved with the buttons available (e.g. shift+ track maybe?)

**Comment by git-moss** [comment]
I guess you use a Push 1. There are 2 ways to go up:
1) Press the eigth button of the second row.
2) Long press any of the first buttons.

This works as well for layers and devices.

**Comment by junglegobs** [comment]
Sorry to bring this up again, but I don't think this is in the documentation or the youtube videos? Could be useful to add it if not?
