### ISSUE TITLE
using the drive with screen reader en reapper end x-toutch compact

### ISSUE THREAD

**Issue by luanmusical** [git-moss/DrivenByMoss-Documentation#33]
Hi, I'm visually impaired and I use screens reader, and all the actions on my x-touch compact reader are readers approximated by the drive and the reader. however, when I press, for example, the key corresponding to channel sends, the message corresponding to what I pressed, however or unidentified screen reader, appears on the screen. it only says notification but doesn't say which one! would be any possible reading so that these messages can appear or reader read?? since now

**Comment by luanmusical** [comment]
I take the opportunity to ask if it would be possible to include the BERINGER  x-touch compact in the factory profiles

**Comment by git-moss** [comment]
Puh, tough question. Might be difficult since Java user interfaces are mixed with Reaper ones. Does the DrivenByMoss window work for you? Can your reader e.g. get the labels / content?

Regarding the second question, the answer is no, since I only support devices which I own for testing.
