### ISSUE TITLE
OSC - how to handle other than "all 8 tracks"

### ISSUE THREAD

**Issue by henning** [git-moss/DrivenByMoss-Documentation#37]
Hi, 
I would like to build a mixer and an "arm track controller"(i want to have  a screen that shows me the record arm state of *all* my tracks and toggle them all on for recording sessions where I want to record all my synths and their midi while jamming) for a project with more than 8 tracks, with some OSC toolkit, either touch OSC or Openstagecontrol.

But reading the docs the selection of tracks seems to be reduced to just 8 tracks, and I dont understand exactly what that means and if/how I can get access to all tracks of the project. 

Is that something that I can change on the OSC client I want to create, or would it require to extend the DrivenByMoss sourcecode to get  access all tracks of a project at once? Or is it even something that is fixed in the Bitwig API that tracks can always only be handled in chunks of 8 and never all at once with some ID from 1 to amount of tracks in the project?

**Comment by git-moss** [comment]
There is the concept of pages. By default you have pages of 8 items (tracks, devices,  etc.) and commands to move to the previous/next item page. With the OSC implementation you can configure the page size in the settings. You can increase it till 200, which means you can address 200 tracks without changing the page.

**Comment by henning** [comment]
ok, so that means when adressing the tracks after adjusting this setting the range that is given in many places of the docs saying "1-8" would be 1-200 or whatever else I set it to, correct?

if you let this open I might try to adjust the documentation with this information here and provide a patch to the docs...

**Comment by henning** [comment]
Also, thanks for the quick reply! 

Just some more things I am not sure with yet:

Is my assumption correct, that via OSC I will not be able to see this mentioned page size number, so i have to know it in my OSC client?

And last but not least, can I somewhere see the total number of tracks in the project somewhere?

I checked for both of these in the docs but cannot find it, so I assume I will have to know it before hand or probe it with multiple `/track/{1-8/200}/exists` request, right?

**Comment by git-moss** [comment]
All your assumptions are correct.

Regarding your question, why there is no track/count parameter: this is how those OSC client tools (like open Stage Control or TouchOSC) normally work: you do not create elements but instead they are all there and you active/show them with e.g. the exists parameter. See my Open Stage Control template which is part of the DrivenByMoss download.
