### ISSUE TITLE
Relative scaling on Generic Flexi

### ISSUE THREAD

**Issue by cordovero** [git-moss/DrivenByMoss-Documentation#38]
Relative scaling doesn't seem to be working with, for example "selected track send 1". Upon changing track and modifying send, values jump. Any ideas for a solution? 

P.S. huge fan of your work Moss!

**Comment by git-moss** [comment]
Thanks! Did you select relative scaling in the Bitwig settings (at the very top of the controller configuration pane).

**Comment by cordovero** [comment]
Yes, and I tried the different options in the Bitwig settings but the values still jump in the same way.

**Comment by git-moss** [comment]
I just did some tests and cannot reproduce your issue. This is with latest Bitwig 5.0.10.
Did this only happen with Sends?

**Comment by cordovero** [comment]
That's strange... I just tried again, with the laster Bitwig 5.0.10 and I still have the issue. This is what my flexi setting looks like for the specific CC. The values still jump upon changing track and modifying the same send.

<img width="540" alt="Screenshot 2023-09-30 at 10 24 43" src="https://github.com/git-moss/DrivenByMoss-Documentation/assets/106381195/1173b557-be98-49cb-bf2c-a13000bde194">

**Comment by git-moss** [comment]
Strrange, that's basically the settings I tested with. And you are fully sure the mode setting on top of this page is correct? Can you post a screenshot of it as well?
Since you use the Launch Control XL, have you seen that I have a native implementation for it as well?

**Comment by cordovero** [comment]
Relative scaling is always selected. I've been using your implementation for it, and it's been wonderful, but I'm trying to set it up for a project in which I need direct control of many sends for each selected track, so I've been trying with flexi, but this value jump has made it very difficult (also, is there any way to get light feedback while using flexi? For example for the selected track button to light up?).

<img width="754" alt="Screenshot 2023-10-02 at 10 18 52" src="https://github.com/git-moss/DrivenByMoss-Documentation/assets/106381195/5aeb5c03-80f1-4257-ba56-ea915f2da87d">

**Comment by git-moss** [comment]
Sorry, currently no idea why it does not work for you.
