### ISSUE TITLE
AKAI APC-20

### ISSUE THREAD

**Issue by klymenkor** [git-moss/DrivenByMoss-Documentation#39]
Greetings! Thank you for your work!

 Do you plan to add support for AKAI APC-20? Ma be not a big deal.. Unfort, it doesnt work with APC-40 config... The process crashes when one changes master fader. All other buttons don't show any visible effect(

**Comment by klymenkor** [comment]
My fault, there are some logs on REC button click also.. 
<img width="1512" alt="Screenshot 2023-10-23 at 15 07 04" src="https://github.com/git-moss/DrivenByMoss-Documentation/assets/133672956/9f7e1a64-73e8-4680-9029-d3c2eb1041ce">

**Comment by git-moss** [comment]
Sorry, no.
