### ISSUE TITLE
Does this currently work for the Arturia Beat Step Pro?

### ISSUE THREAD

**Issue by naught101** [git-moss/DrivenByMoss-Documentation#4]
I can see that previous versions listed the BS and the BSP, but the latest version only lists the BS. I tried installing it anyway, and I can add a device as a Beat Step, but it doesn't respond to transport controls (I'm not entirely sure if it's meant to). I would really like to be able to hit play on my laptop and have the BSP start playing. Is this possible currently?

I'm using Bitwig 3.1.2. BSP firmware is up to date.

**Comment by git-moss** [comment]
I removed the BSP support since it had too many issue. You can look into the Generic Flexi which gives you the option to map what you want.
