### ISSUE TITLE
faderfox ec4 wrong download type

### ISSUE THREAD

**Issue by madskjeldgaard** [git-moss/DrivenByMoss-Documentation#40]
Hi! Thanks for all of this amazing work!! 

I tried following your instructions for uploading your sysex template to the faderfox ec4 I have. The docs mention that it should be using firmware version 2 at least, but I can't find any versions above 1.01 on the FF website. Is this a mistake?

**Comment by git-moss** [comment]
It is not yet released (as is DrivenByMoss 22).
