### ISSUE TITLE
Link tempo on Launchkey mini Mk3

### ISSUE THREAD

**Issue by JARA99** [git-moss/DrivenByMoss-Documentation#7]
Hi, first of all, thank you for sharing this amazing work!

I am running Reaper on a Manjaro Linux machine, and I was wondering, how do I get sync the integrated arpeggiator in my LaunchKey mini mk3 to my DAW, so I can get the same tempo. I am not sure if that's a feature of this driver and it's not working for me, or if it is a missing feature, however, I open the issue.

Thank you again!

**Comment by git-moss** [comment]
Haven't tested that. You can try to send MIDI clock to the device. For that you need to activate the MIDI output in Reaper and check the box "Send clock this device" but then you can't use DrivenByMoss.
